### ISSUE TITLE
 Error: PDU length was too large (1744896102, maximum is 16384).

### ISSUE THREAD

**Issue by ptorrent** [farhadi/node-smpp#109]
Hello there !

Thanks for your great work !

![image](https://user-images.githubusercontent.com/6083644/65673418-0e624100-e04b-11e9-904a-5e8edea3c6cf.png)

Is there a way to prevent process shutdown on this error  (without process.uncaughtException) ?

Thanks for your support !

**Comment by ptorrent** [comment]
Maybe session.on('error', function(){ do the trick ?

**Comment by juliangut** [comment]
Hi @ptorrent 

I'm going to start by saying that although this library accepts [max PDU length up to 16KB](https://github.com/farhadi/node-smpp/commit/6015fe51836e9a458d4604661434471d9b137677) SMPP protocol actually allows 4 octets for `command_length` (>536MB)

16KB may seam as an arbitrary decision for max length, and it actually is, but a sane one. It seams absurd to allow a PDU to be longer than 536MB. To put some perspective on the numbers Victo Hugo's _Les Misérables_ is about 3MB long as plain text

So back to your scenario, you're trying to send a >218MB PDU, following previous example, it's 72 times that book, I really hope you have a reason for that

Anyway if you **really** want to do it, because it is not a mistake, you can try be changing `PDU.maxLength` (https://github.com/farhadi/node-smpp/blob/master/lib/pdu.js#L204) before using the library

```js
const smpp = require('smpp');

smpp.PDU.maxLength = 2000000000; // 250MB approx

// your code
```

**Comment by ptorrent** [comment]
Hello !

THansk a lot for your answer.

The problem is that this request does not come from me! I have to investigate where it can come from... But the problem is, it'scrashing my script.

Do you think that 
```
Maybe session.on('error', function(){ })

```
solve the script scrashing ?

**Comment by juliangut** [comment]
yes, it you can react to that error and prevent crashing with that code (https://github.com/farhadi/node-smpp/blob/master/lib/smpp.js#L63)

But I urge you to also consider finding out what is going on with that PDU, contact the sender

**Comment by ptorrent** [comment]
Yes  thanks ! I will investigate into it.

Thanks again, I close this "issue".

Have a nice day

**Comment by niteshtripathi1234** [comment]
Thanks for Your Work,
Please let me know how Command_lenght is Calculated, what was the reason for exceeding the limit.
