### ISSUE TITLE
TypeError: value is out of bounds

### ISSUE THREAD

**Issue by Dexus** [farhadi/node-smpp#12]
```
buffer.js:705
    throw TypeError('value is out of bounds');
          ^
TypeError: value is out of bounds
    at TypeError (<anonymous>)
    at checkInt (buffer.js:705:11)
    at Buffer.writeUInt32BE (buffer.js:748:5)
    at PDU.<anonymous> (/var/node-demo/node_modules/smpp/lib/pdu.js:122:10)
    at Array.forEach (native)
    at PDU._initBuffer (/var/node-demo/node_modules/smpp/lib/pdu.js:121:16)
    at PDU.toBuffer (/var/node-demo/node_modules/smpp/lib/pdu.js:144:20)
    at Session.send (/var/node-demo/node_modules/smpp/lib/smpp.js:74:24)
    at Session.<anonymous> (/var/node-demo/server-smpp.js:25:11)
    at Session.emit (events.js:95:17)
```

Node: v0.10.31
"smpp": "^0.1.0"

**Comment by farhadi** [comment]
@hkulekci node-smpp doesn't support Single Shift Character Sets for other languages. You can either use unicode encoding or manually encode your string in a buffer and pass this buffer as message parameter.

**Comment by farhadi** [comment]
@mzalazar in case you want to send binary data in short_message you should pass a Buffer instead of a string to short_message parameter.

**Comment by farhadi** [comment]
@Dexus can you provide me a code to reproduce the issue?

**Comment by lillem4n** [comment]
I am having the same issue with this PDU:
00 00 00 3c 00 00 00 04 00 00 00 00 00 00 00 02 00 01 00 34 36 37 30 31 31 33 33 31 31 31 00 01 01 34 36 37 30 39 37 37 31 33 33 37 00 00 00 00 00 00 00 00 00 00 04 74 65 73 74 00

The problem is that the command_length is set to 60, but in pdu.js this row:
  
    while (offset < this.command_length)

triggers, since offset only have arrived at 59. That makes tlvId = buffer.readUInt16BE(offset) choke and throw that error. If you manually count the octets, the length of the command is actually 60, so it is an error in this modules code.

However, as a larger issue; this kind of errors with PDUs should in my opinion not crash the whole application, but instead return a generic error PDU and close the current session.

**Comment by lillem4n** [comment]
The issue seems to be that the short_message parameter is said to be 4 in length, but actually is terminated by a NULL octet. Maybe this is invalid? I tried this exact PDU with another software and it accepted it.

**Comment by lillem4n** [comment]
The specification reads: "An Octet String is a sequence of octets not necessarily terminated with a NULL octet. Such fields using Octet String encoding, typically represent fields that can be used to encode raw binary data. In all circumstances, the field will be either a fixed length field or explicit length field where another field indicates the length of the Octet String field. An example of this is the short_message field
of the submit_sm PDU that is Octet String encoded and the previous message_length field specifies its length."

I guess it can be interpreted as it CAN be terminated with a NULL octet and in that case that ending NULL octet is not a part of the value and hence not calculated with the length value.

Since the "short_message" always is last of the parameters, it should be safe to make a check if the following octet directly after the buffer type is a NULL octet, and if it is, include it in the length calculations.

It is ugly and it is horrible. But so is the SMPP protocol. :p

**Comment by lillem4n** [comment]
It could also be determined by comparing the total size of the PDU with the calculated after the parameters are done. I dont know whats best.

**Comment by mzalazar** [comment]
@lillem4n thanks for your comments, they're very usefull to me ;-)

**Comment by farhadi** [comment]
@lillem4n
Based on the specification (4.7.26 short_message) the pdu you mentioned should be considered a malformed pdu:
> The value of the sm_length field indicates the explicit number of octets that the short_message field contains. NULL terminator octets (for ASCII content) should not be used in this field but if a NULL octet is included with the short_message data, then this octet MUST be included in the sm_length field.

However the code should not fail on a malformed pdu.
I fixed this issue by checking that there is at least 4 more bytes before reading a TLV parameter at 6e6667e42e5cb87ae4b272e45185b8ef124482ef.
