### ISSUE TITLE
Forward SMS from SMPP server to another SMPP server

### ISSUE THREAD

**Issue by modellhr** [farhadi/node-smpp#123]
hello @juliangut ,

Is it possible to forward sms from node-smpp server to another SMPP server? 
For example in current scenario, once sms received here is the way i am forwarding to other SMPP server.

```node
session.on("submit_sm", async pdu => {
    // console.log("Srv: received submit_sm");
    let data = {
      to: pdu.destination_addr,
      from:pdu.source_addr,
      message: pdu.short_message.message
    }
    let  messageId;
    request.post({
       url: 'http://smpp-server-url/api/smppServers',
      form: data},
    function (err, httpResponse, body) {
      if (err) {
        session.send(
          err,
          pdu.response({
            command_status: smpp.ESME_RINVSRCADR
          })
        );
        return;
      }else if(httpResponse && httpResponse.body){
        let resp = JSON.parse(httpResponse.body)
        messageId = resp.message_id;

        let pdu_response = pdu.response();
        pdu_response['message_id']=messageId

        session.send(pdu_response);
      }else{
        session.send(
          pdu.response({
            command_status: smpp.ESME_RINVSRCADR
          })
        );
      }
    })
});
```

But not sure in this was how to receive DLR and forward the same back to client. Is there a way to perform this action?

**Comment by juliangut** [comment]
Hi @modellhr, I've edited the issue description so that code is formatted by github

To answer your question, yes it is perfectly possible to forward incoming communication to another SMPP server, effectively acting as a proxy. If the forwarding server is a SMPP server, SMPP protocol should be used to forward the messages' PDU to and from your provider, but that is not what you're doing

In your example I'll assume you are actually trying to forward messages to an HTTP server (because of `request.post({`), so you can send a payload (`data`) to provider and return submit_sm_resp to your client based on the status, but won't be directly able to provide deliver_sm to your client unless you develop a way to collect DRs from your provider and then hand them on deliver_sm messages

If you follow the HTTP provider way, I'd suggest to include a webhook to collect DRs to send them to a queue, and make your SMPP server listen to that queue in order to send deliver_sm messages to clients
If you go for the all-SMPP way, you should connect to your provider using SMPP and then send messages back and forth between your client and your provider

In both cases, in between forwarding messages, you should do something with them, otherwise what is the point on being a plain proxy

**Comment by modellhr** [comment]
Ok. I am storing the DLRs in RabbitMQ and then consuming from there. 
but i am getting this error : 

```
Cannot read property 'id' of undefined
this.command_id = commands[command].id;  (line 22 of pdu.js)
```

here is how i am consuming:

```
ch.consume('delivery-reports', function(msg){
    let message = msg.content.toString()
    message = JSON.parse(message)
    console.log(message)       // this shows the delivery-report
    session.send(new smpp.PDU('deliver_sm', {
      esm_class: 4,
      short_message: message.short_message.message,
      source_addr: message.destination_addr,
      destination_addr: message.source_addr,
      }));
 }, {noAck: true})
```
any idea what went wrong?

**Comment by juliangut** [comment]
I see no reason for that code to fail.

I'd suggest to you to debug/breakpoint or console.log "command" at pdu.js:16 so you can see what is the value there, because `commands['deliver_sm']` definitely exists so the error might be in another place

**Comment by modellhr** [comment]
Thanks @juliangut , i traced the piece of code that causes this issue.
On server side, upon receiving `delivery_sm_resp`, when i send the PDU response back to client here is what i found.

```
 session.on("deliver_sm_resp", function (pdu) {
    console.log("Srv: session received deliver_sm_resp");
    session.send(pdu.response());
  });
```

in console, command shows as  `deliver_sm_resp_resp`

Am i doing something wrong while sending pdu.response() back?

**Comment by juliangut** [comment]
> Am i doing something wrong while sending pdu.response() back?

Yes, your problem is `deliver_sm_resp` is the end of the communication and so you should not respond to it

When you call pdu.response() the resulting command is composed of current_command + '_resp' sufix, thus the non existent `deliver_sm_resp_resp`

**Comment by modellhr** [comment]
Yes that was the issue. After removing that `deliver_sm_response` its working fine but i am getting multiple DLRs for same message ID (same status)
if i bind and send message first time, i get one dlr, if i send second message, i get 2 DLR and if send third message, i get 3 DLRs.

```
 session.on('pdu', function(pdu){
    if(pdu.command === 'deliver_sm'){
      // dlr
      console.log(pdu)
      
      session.deliver_sm_resp({
        sequence_number: pdu.sequence_number
    });
    }
  })
```
though i am responding to server with `deliver_sm_resp` , how come i am receiving multiple DLRs?

**Comment by modellhr** [comment]
Thanks @juliangut ,  issue has been resolved. For above mentioned comment, actually i was calling `session.deliver_sm_resp` inside `session.on('submit_sm')` method. So by placing this outside of `submit_sm` function,  it starts working perfectly.

**Comment by juliangut** [comment]
I'm glad it got solved, I'm closing this issue

**Comment by fardhana** [comment]
hi @modellhr , i have question. hope you willing to answer it.
Regarding dlr, how you link between rabbitmq consumer and session bind to smpp server?

Thanks!

**Comment by modellhr** [comment]
Hi @fardhana ,
In my case, i have one queue with multiple consumers. Rather than session, i would prefer to have 1 queue for 1 host. As i came across many SMSC who sent DLR only on first time binded session. 
But in case if you are interested to have 1 queue for each session, you could then add some unique custom prop to session object while binding and assert a queue with that unique id.

**Comment by fardhana** [comment]
Hi @modellhr ,
Thanks for the reply. 
In my case, one SMPP server will handle multiple client and session. And i also using AMQP for listen DR callback from HTTP Server. 

That's why i asking how single consumer can mapping a message queue to correct session, it's will relate with next question where is the best approach to store the mapping of client id / system id with session.

I end up to use global variable contains array key system_id with value session.
