### ISSUE TITLE
Problem with Spanish characters

### ISSUE THREAD

**Issue by Kcamplone** [farhadi/node-smpp#125]
Hi there

I'm using this library as a client to connect with a SMSC gateway here in Uruguay, I'm using ASCII as default encondig but for some reason characters like á ó don't come with the accent.

Example: 

Sending: "Hola Kevin, ¿cómo estas? esta es una campaña de prueba. Hoy correré 10KM! à"
I receive: Hola Kevin, ¿c**o**mo estas? esta es una campaña de prueba. Hoy correré 10KM! à

I saw the code and I thought it would detect automatically GSM_ES but its not.

I tried smpp.encodings.default = 'GSM_ES' but its not working;

any advice?

thanks

**Comment by juliangut** [comment]
Hi @Kcamplone 

First of thanks for using the library

About your question, using GSM language shift tables is not as straight forward as you'd expect:

When encoding GSM with Language Shift Tables for a language, in your case Spanish, [data_coding remains GMS|ASCII](https://github.com/farhadi/node-smpp/blob/master/lib/defs.js#L1389). Actually what tells your provider you're sending GSM employing shift tables is the presence of a specific UDH, in the case for Spanish it's `Buffer.from([0x03, 0x25, 0x01, 0x02])`

You can see it in the examples: https://github.com/farhadi/node-smpp/blob/master/test/filters.js#L99

But bear in mind that your SMSC provider has to be able to accept and understand this UDH, otherwise your message will still be considered GSM and depending on how your SMSC works you can receive it:

- truncated, _Hola Kevin, ¿cmo estas? esta es una campaña de prueba. Hoy correré 10KM! à_
- with undesirable chars, _Hola Kevin, ¿c֍mo estas? esta es una campaña de prueba. Hoy correré 10KM! à_
- or, as it appears in your case, changed to closest valid GSM char, _Hola Kevin, ¿c**o**mo estas? esta es una campaña de prueba. Hoy correré 10KM! à_

**Comment by Kcamplone** [comment]
I understand, thanks for your response!

I asked them about the encondig, and they told me they use gsm7, but I think this lib doesn't support it.

**Comment by juliangut** [comment]
GSM7 is [GSM03.38](https://en.wikipedia.org/wiki/GSM_03.38#GSM_7-bit_default_alphabet_and_extension_table_of_3GPP_TS_23.038_.2F_GSM_03.38) or what is commonly referred as GSM encoding, and is this library's default encoding

From that answer what I infer is that they do not support [language shift tables](https://en.wikipedia.org/wiki/GSM_03.38#National_language_shift_tables)

**Comment by juliangut** [comment]
I think we can close this issue now
