### ISSUE TITLE
How to get port number of nodesmpp server in runtime.

### ISSUE THREAD

**Issue by ayalabs** [farhadi/node-smpp#143]
I have stored port no in db so that i can get multiple instance of node smpp.
Now how i can get the port number while i am receiving pdu or bind

pool.getConnection(function(err,connection) {
    let sql="SELECT * FROM channels";
    connection.query(sql, function (err, result) {
      // console.log(result.length);
        for (let i = 0; i <= result.length; i++) {
            //`smpp://${ip}:${port}`
            smppsw[i]= smpp.createServer(function(session) {
                common(session);   
            });
          console.log(result[i]['port']);
            smppsw[i].listen(result[i]['port']);
        }
    });
});

**Comment by juliangut** [comment]
Hi @ayalabs 

I'm afraid you cannot do just that because each process running node smpp must be listening for connections from a specific port

You can try spawning [child processes](https://nodejs.org/api/child_process.html) each one of those could listen in a different port, though I haven't done this myself

If you want to set up a different instance (in different ports) for each client, maybe a better solution is to control your incoming connections by the system_id they use for the binding

**Comment by juliangut** [comment]
I feel the answer can't go any further so I'm closing this

**Comment by ayalabs** [comment]
Thanks for supporting
