### ISSUE TITLE
Strange DLR handling issue

### ISSUE THREAD

**Issue by ajamous** [farhadi/node-smpp#169]
I’m currently facing a strange issue and would like the community opinion. 

The problem we are facing that smpp server response to TCP packet (deliver_sm) successfully but we are unable to find it in our logs, while at the same time stamp other messages / dlrs are coming in without any issues and they are logged to log file and relayed to sender / client properly. 

1) We need to understand why some of these responses and submissions are not logged as they should to the log file. 

2) how come the NodeJS smpp server responds to the  deliver_sm OK without relaying it. 

I have already checked everything related to hardware and we were not able to find any unusual High load Issues. I have also tried to reproduce the issues in several test scenarios but we failed to reproduce it. 

So the main issue: some &quot;not all&quot; messages DLR is not relayed and not logged while SMPP server actually received the DLR and Responded with Deliver_SM Response OK.  Any ideas ?

**Comment by juliangut** [comment]
Hi @ajamous 

The library should not automatically respond to deliver_sm PDUs with deliver_sm_resp, your `.on('deliver_sm', function (pdu) {` should be the one sending the response PDU being your code the only one knowing the command_status for the response

I advise you to review your handling of deliver_sm PDUs because there may be a path through which you are missing those logs. Or even review if the problem can be the log process itself, I've sometimes seen logging systems loosing messages

**Comment by ajamous** [comment]
Thanks @juliangut, you're right it was on my side. thx
